### ISSUE TITLE
Add an eraser

### ISSUE THREAD

**Issue by davelab6** [lisezmoi/scri.ch#26]
http://scri.ch/m6j has a few mistakes. I love the minimalism, but I'd love an eraser tool to make the 'whiteboard' effect a little more useful which I don't think would ruin the minimalism :)

**Comment by raphaelbastide** [comment]
Cool drawing ;-)
We strongly believe that the absence of eraser tool is a feature, not a mistake.
1. We love the concept of “napkin drawing”, quick and dirty, crossing-out is fine and sexy!
2. We recommend the use of the “Save” button if you want to go back in a previous version of the drawing. Then you can basically refresh your page to erase your last additions.
3. A lot of existing services allows to draw, erase, change pen stroke and colours. We want to keep our radical approach to drawing in order to make the experience and the UI as simple as possible.

**Comment by davelab6** [comment]
On 4 April 2014 15:11, Raphaël Bastide notifications@github.com wrote:

> We recommend the use of the “Save” button if you want to go back in a
> previous version of the drawing. Then you can basically refresh your page
> to erase your last additions.

Ah, PERFECT - please document this technique in the about / faq page and
close this issue :)
